import { and, desc, eq, isNull } from 'drizzle-orm'

import type { Database } from '@louez/db'
import { apiKeys } from '@louez/db/schema'

import { ApiServiceError } from './errors'

const API_KEY_SCOPES = [
  'products:read',
  'customers:read',
  'reservations:read',
  'availability:read',
] as const

export type ApiKeyScope = (typeof API_KEY_SCOPES)[number]

export function isValidScope(scope: string): scope is ApiKeyScope {
  return (API_KEY_SCOPES as readonly string[]).includes(scope)
}

/**
 * Generate a cryptographically random string.
 */
function randomString(length: number): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
  const bytes = new Uint8Array(length)
  crypto.getRandomValues(bytes)
  return Array.from(bytes, (b) => chars[b % chars.length]).join('')
}

/**
 * Generate a random API key with a recognizable prefix.
 * Format: lz_live_<32 chars>
 */
function generateApiKey(): { raw: string; prefix: string } {
  const raw = `lz_live_${randomString(32)}`
  const prefix = raw.slice(0, 8)
  return { raw, prefix }
}

/**
 * Hash an API key using SHA-256 (Web Crypto API).
 */
async function hashKey(raw: string): Promise<string> {
  const encoder = new TextEncoder()
  const data = encoder.encode(raw)
  const hashBuffer = await crypto.subtle.digest('SHA-256', data)
  const hashArray = Array.from(new Uint8Array(hashBuffer))
  return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('')
}

export async function createApiKey(params: {
  db: Database
  storeId: string
  userId: string
  name: string
  scopes: string[]
  expiresAt?: Date | null
}): Promise<{ id: string; key: string; prefix: string }> {
  const { db, storeId, userId, name, scopes, expiresAt } = params

  for (const scope of scopes) {
    if (!isValidScope(scope)) {
      throw new ApiServiceError('BAD_REQUEST', `Invalid scope: ${scope}`)
    }
  }

  const { raw, prefix } = generateApiKey()
  const keyHash = await hashKey(raw)

  // The id is auto-generated by schema's $defaultFn (nanoid)
  await db.insert(apiKeys).values({
    storeId,
    createdBy: userId,
    name,
    keyPrefix: prefix,
    keyHash,
    scopes,
    expiresAt: expiresAt ?? null,
  })

  // Retrieve the created key by its unique hash
  const [created] = await db
    .select({ id: apiKeys.id })
    .from(apiKeys)
    .where(eq(apiKeys.keyHash, keyHash))
    .limit(1)

  return { id: created!.id, key: raw, prefix }
}

export async function listApiKeys(params: {
  db: Database
  storeId: string
}) {
  return db
    .select({
      id: apiKeys.id,
      name: apiKeys.name,
      keyPrefix: apiKeys.keyPrefix,
      scopes: apiKeys.scopes,
      lastUsedAt: apiKeys.lastUsedAt,
      expiresAt: apiKeys.expiresAt,
      createdAt: apiKeys.createdAt,
      revokedAt: apiKeys.revokedAt,
    })
    .from(apiKeys)
    .where(
      and(
        eq(apiKeys.storeId, params.storeId),
        isNull(apiKeys.revokedAt),
      ),
    )
    .orderBy(desc(apiKeys.createdAt))
}

export async function revokeApiKey(params: {
  db: Database
  storeId: string
  keyId: string
}) {
  const result = await params.db
    .update(apiKeys)
    .set({ revokedAt: new Date() })
    .where(
      and(
        eq(apiKeys.id, params.keyId),
        eq(apiKeys.storeId, params.storeId),
        isNull(apiKeys.revokedAt),
      ),
    )

  if (result[0].affectedRows === 0) {
    throw new ApiServiceError('NOT_FOUND', 'API key not found')
  }
}

/**
 * Validate an API key and return the associated store context.
 * Updates lastUsedAt on successful validation.
 */
export async function validateApiKey(params: {
  db: Database
  rawKey: string
}): Promise<{
  storeId: string
  scopes: string[]
  keyId: string
} | null> {
  const keyHash = await hashKey(params.rawKey)

  const rows = await params.db
    .select({
      id: apiKeys.id,
      storeId: apiKeys.storeId,
      scopes: apiKeys.scopes,
      expiresAt: apiKeys.expiresAt,
      revokedAt: apiKeys.revokedAt,
    })
    .from(apiKeys)
    .where(eq(apiKeys.keyHash, keyHash))
    .limit(1)

  const row = rows[0]
  if (!row) return null
  if (row.revokedAt) return null
  if (row.expiresAt && row.expiresAt < new Date()) return null

  // Update lastUsedAt in background (non-blocking)
  void params.db
    .update(apiKeys)
    .set({ lastUsedAt: new Date() })
    .where(eq(apiKeys.id, row.id))
    .then(() => {})
    .catch(() => {})

  return {
    storeId: row.storeId,
    scopes: row.scopes,
    keyId: row.id,
  }
}
